# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := GLTools

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

GLTools: 
	@echo "==== Building GLTools ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f GLTools.make

clean:
	@${MAKE} --no-print-directory -C . -f GLTools.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLTools"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
