# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := framework tutorial1 FragPosition VertexColors vertPositionOffset cpuPositionOffset fragChangeColor vertCalcOffset vertCalcOffset_Remixed

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

framework: 
	@echo "==== Building framework ($(config)) ===="
	@${MAKE} --no-print-directory -C common -f Makefile

tutorial1: framework
	@echo "==== Building tutorial1 ($(config)) ===="
	@${MAKE} --no-print-directory -C tutorial1 -f Makefile

FragPosition: framework
	@echo "==== Building FragPosition ($(config)) ===="
	@${MAKE} --no-print-directory -C tutorial2 -f FragPosition.make

VertexColors: framework
	@echo "==== Building VertexColors ($(config)) ===="
	@${MAKE} --no-print-directory -C tutorial2 -f VertexColors.make

vertPositionOffset: framework
	@echo "==== Building vertPositionOffset ($(config)) ===="
	@${MAKE} --no-print-directory -C tutorial3 -f vertPositionOffset.make

cpuPositionOffset: framework
	@echo "==== Building cpuPositionOffset ($(config)) ===="
	@${MAKE} --no-print-directory -C tutorial3 -f cpuPositionOffset.make

fragChangeColor: framework
	@echo "==== Building fragChangeColor ($(config)) ===="
	@${MAKE} --no-print-directory -C tutorial3 -f fragChangeColor.make

vertCalcOffset: framework
	@echo "==== Building vertCalcOffset ($(config)) ===="
	@${MAKE} --no-print-directory -C tutorial3 -f vertCalcOffset.make

vertCalcOffset_Remixed: framework
	@echo "==== Building vertCalcOffset_Remixed ($(config)) ===="
	@${MAKE} --no-print-directory -C tutorial3 -f vertCalcOffset_Remixed.make

clean:
	@${MAKE} --no-print-directory -C common -f Makefile clean
	@${MAKE} --no-print-directory -C tutorial1 -f Makefile clean
	@${MAKE} --no-print-directory -C tutorial2 -f FragPosition.make clean
	@${MAKE} --no-print-directory -C tutorial2 -f VertexColors.make clean
	@${MAKE} --no-print-directory -C tutorial3 -f vertPositionOffset.make clean
	@${MAKE} --no-print-directory -C tutorial3 -f cpuPositionOffset.make clean
	@${MAKE} --no-print-directory -C tutorial3 -f fragChangeColor.make clean
	@${MAKE} --no-print-directory -C tutorial3 -f vertCalcOffset.make clean
	@${MAKE} --no-print-directory -C tutorial3 -f vertCalcOffset_Remixed.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   framework"
	@echo "   tutorial1"
	@echo "   FragPosition"
	@echo "   VertexColors"
	@echo "   vertPositionOffset"
	@echo "   cpuPositionOffset"
	@echo "   fragChangeColor"
	@echo "   vertCalcOffset"
	@echo "   vertCalcOffset_Remixed"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
